---
- name: Deploy Sutter Health Multi-Tier Application
  hosts: localhost
  
  roles:
    - role: cherwell_create_ticket

- name: Setup VLANs and ports on switches
  hosts: leafs
  roles:
    - role: leaf_switch

- name: depoy multi-tier web application
  hosts: webservers
  roles:
    - role: app
    - role: web  

# Setup LB tier
- name: setup LB tier
  hosts: frontends
  become: yes
  roles:
    - lb
   
# Setup Firewall for Application 
- name: setup firewall tier
  hosts: pan-fw
  become: yes
  roles:
    - firewall

# Create CMDB Record
- name: create ITSM ticket
  hosts: cherwell
  roles:
    - cherwell_create_cmdb_record

# Close Cherwell ITSM Ticket
- name: cherwell create ITSM ticket
  hosts: cherwell
  roles:
    - cherwell_close_ticket

