---
## This playbook deploys a multi-tier application and configures the infrastructure

# Create ITSM Ticket
- name: create ITSM ticket
  hosts: localhost
  roles:
    - cherwell_create_ticket

# Provision VM
- name: provision vm
  hosts: hypervisors
  roles:
    - provision_vm

# Validate or Setup Networking for Application Support
- name: setup VLANs and ports on switches
  hosts: leafs
  roles:
    - leaf_switch

# Deploy a simple web application
- name: depoy multi-tier web application
  hosts: webservers
  roles:
    - app
    - web  

# Setup LB tier
- name: setup LB tier
  hosts: frontends
  roles:
    - lb
   
# Setup Firewall for Application 
- name: setup firewall 
  hosts: pan-fw
  roles:
    - firewall

# Create CMDB Record
- name: create ITSM ticket
  hosts: cherwell
  roles:
    - cherwell_create_cmdb_record

# Close Cherwell ITSM Ticket
- name: cherwell create ITSM ticket
  hosts: cherwell
  roles:
    - cherwell_close_ticket

