#  VLAN Configuration
- name: ensure VLANs exist on switches
  host: "{{ inventory_hostname }}"
  nxos_vlan: 
    vlan_range: "{{ vlans }}"
    state: present 
    transport: nxapi

- name: ensure names exist for important vlans
  host: "{{ inventory_hostname }}"
  nxos_vlan: 
    vlan_id: "{{ item.vlan_id }}" 
    name: "{{ item.name }}"
    state: present
  with_items: named_leaf_vlans

# Layer 2 switchport Configuration
- name: L2 config for uplinks
  host: "{{ inventory_hostname }}"
  nxos_switchport: 
    interface: "{{ item }}"
    mode: trunk 
    native_vlan: 99 
    trunk_vlans: 2-19
  with_items: uplink_interfaces

# Layer 3 Configuration
- name: create logical vlan interfaces as default gateways
  host: "{{ inventory_hostname }}"
  nxos_interface: 
    interface:"{{ item }}"
  with_items: logical_interfaces_to_create

- name: assign IP addresses
  host: "{{ inventory_hostname }}"
  nxos_ipv4_interface: 
    interface: "{{ item.interface }}"
    ip_addr: "{{ item.ip }}"
    mask: "{{ item.mask }}"
  with_items: layer3ip