- name: Create Cherwell CMDB record
  uri:
    url: "https://cherwell.sutterhealth.org/CherwellAPI/api/V1/create_cmdb_record"
    method: POST
    body:
      payload: "{{ payload }}"
    body_format: json
    user: "{{ cherwell_user }}"
    password: "{{ cherwell_password }}"
    status_code: 200  