- name: Create Cherwell CMDB record
  uri:
    url: "{{ cherwell_cmdb_url }}"
    method: POST
    body:
      payload: "{{ payload }}"
    body_format: json
    user: "{{ cherwell_user }}"
    password: "{{ cherwell_password }}"
    status_code: 200  