---
# tasks file for web

- name: install httpd
  yum:
    name: httpd
    state: latest

- name: Install httpd configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'

- name: start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true
    