- name: Close Cherwell ticket
  uri:
    url: "{{ cherwell_ticket_url }}"
    method: POST
    body:
      ticket: "{{ ticket }}"
      comment: application deployment successful
    body_format: json
    user: "{{ cherwell_user }}"
    password: "{{ cherwell_password }}"
    status_code: 200  